spring:
  application:
    name: discovery-service

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0